name: paynal
description: Dart STOMP client
version: 0.1.1
repository: https://github.com/ushieru/paynal_dart

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  uuid: 3.0.7
  meta: 1.8.0
  web_socket_channel: 2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
